services:
  web-app:
    build: ./web-app
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mlc
    networks:
      - app-network

  mlc:
    build: ./machine-learning-client
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network


volumes:
  mongo-data:

networks:
  app-network:
