name: MLC Build & Test

on:
  push:
    paths:
      - 'machine-learning-client/**'
  pull_request:
    paths:
      - 'machine-learning-client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine-learning-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run linter (pylint)
        run: pipenv run pylint app.py classify.py
